In [19]:
# import the module
import tweepy

In [20]:
# assign the values accordingly
consumer_key = "cqv47tlAOJYqtaBdP7fw4hzEX"
consumer_secret = "maLecnWc2uAVeQxwoZXgZ9GleSwk4eN674UQtshaN68uwav0lY"
access_token = "1477847685176573953-s5FeJNxaqCZCAi9fFsV6SL2WJUCXOl"
access_token_secret = "RtmzQ0BRtKvRvGC3DstDE2U7E5RlC4bsEVP2AgdjXmdGf"

In [21]:
# authorization of consumer key and consumer secret
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)

In [22]:
auth.access_token
auth.access_token_secret

In [23]:
auth.set_access_token(access_token, access_token_secret)

In [24]:
api = tweepy.API(auth, wait_on_rate_limit=True)
search_words = "Energy Consumption"      #enter your words
new_search = search_words + " -filter:retweets"

In [41]:
import time
from time import sleep

my_followers = []
for tweet in tweepy.Cursor(api.search,q=new_search).items(10000):
    my_followers.append([tweet.created_at, tweet.text,tweet.user.screen_name, tweet.user.location])                                        
    time.sleep(1)

In [42]:
my_followers[0]

[datetime.datetime(2022, 7, 11, 14, 40, 10),
 'The Texas electric grid operator on Monday was calling on companies to lower their energy consumption to reduce the‚Ä¶ https://t.co/MtajKFLTpJ',
 'FMLeaderNews',
 'Flower Mound, Texas']

In [43]:
import pandas as pd
#Creating a dataframe from the tweets list above 
df = pd.DataFrame(my_followers, columns=['created_at','Text', 'Username','Location'])
df

,created_at,Text,Username,Location
0,2022-07-11 14:40:10,The Texas electric grid operator on Monday was...,FMLeaderNews,"Flower Mound, Texas"
1,2022-07-11 14:40:09,The Texas electric grid operator on Monday was...,TheColonyNews,
2,2022-07-11 14:40:09,The Texas electric grid operator on Monday was...,starlocalmedia,"Plano, Texas"
3,2022-07-11 14:40:09,The Texas electric grid operator on Monday was...,Rowlett_News,Rowlett
4,2022-07-11 14:40:09,The Texas electric grid operator on Monday was...,planonewspaper,"Plano, TX"
...,...,...,...,...
3578,2022-07-01 18:32:29,@coreyacj09w @JaimelHemphill @crystalburtonp1 ...,Blackcapitalis,Texas born
3579,2022-07-01 18:27:13,It would be typical to require this with no ef...,EmpireinWinter,
3580,2022-07-01 17:20:02,üè°40% of energy consumption in Europe comes fro...,PaulsonInst,US & China
3581,2022-07-01 16:53:00,Judging Bitcoin by its energy consumption is l...,WSzamosszegi,Maryland
3582,2022-07-01 14:49:39,@rogueonomist Ammar bhai are india/Bangladesh ...,junaiddmir,Nadiya Ke Paar

In [44]:
import re
# Create a function to clean the tweets
def cleanTxt(text):
    text = re.sub('@[A-Za-z0‚Äì9]+', '', text) #Removing @mentions
    text = re.sub('#', '', text) # Removing '#' hash tag
    text = re.sub('RT[\s]+', '', text) # Removing RT
    text = re.sub('https?:\/\/\S+', '', text) # Removing hyperlink
    return text

#applying this function to Text column of our dataframe
#df["Text"] = df["Text"].decode("utf-8")
df["Text"] = df["Text"].apply(cleanTxt)

Sentiment Analysis

In [45]:
import pandas as pd
from nltk.sentiment.vader import SentimentIntensityAnalyzer
from datetime import datetime

In [46]:
vader=SentimentIntensityAnalyzer()

In [47]:
compond=lambda summary: vader.polarity_scores(summary)['compound']
df['Compound']=df['Text'].apply(compond)

negative=lambda summary: vader.polarity_scores(summary)['neg']
df['Negative']=df['Text'].apply(negative)

neutral=lambda summary: vader.polarity_scores(summary)['neu']
df['Neutral']=df['Text'].apply(neutral)

positive=lambda summary: vader.polarity_scores(summary)['pos']
df['Positive']=df['Text'].apply(positive)
df

,created_at,Text,Username,Location,Compound,Negative,Neutral,Positive
0,2022-07-11 14:40:10,The Texas electric grid operator on Monday was...,FMLeaderNews,"Flower Mound, Texas",-0.0258,0.103,0.798,0.099
1,2022-07-11 14:40:09,The Texas electric grid operator on Monday was...,TheColonyNews,,-0.0258,0.103,0.798,0.099
2,2022-07-11 14:40:09,The Texas electric grid operator on Monday was...,starlocalmedia,"Plano, Texas",-0.0258,0.103,0.798,0.099
3,2022-07-11 14:40:09,The Texas electric grid operator on Monday was...,Rowlett_News,Rowlett,-0.0258,0.103,0.798,0.099
4,2022-07-11 14:40:09,The Texas electric grid operator on Monday was...,planonewspaper,"Plano, TX",-0.0258,0.103,0.798,0.099
...,...,...,...,...,...,...,...,...
3578,2022-07-01 18:32:29,1 1) Hands are are washed more frequently.\...,Blackcapitalis,Texas born,0.0000,0.000,1.000,0.000
3579,2022-07-01 18:27:13,It would be typical to require this with no ef...,EmpireinWinter,,-0.0258,0.103,0.798,0.099
3580,2022-07-01 17:20:02,üè°40% of energy consumption in Europe comes fro...,PaulsonInst,US & China,0.2732,0.000,0.896,0.104
3581,2022-07-01 16:53:00,Judging Bitcoin by its energy consumption is l...,WSzamosszegi,Maryland,0.6908,0.000,0.705,0.295
3582,2022-07-01 14:49:39,Ammar bhai are india/Bangladesh also as depen...,junaiddmir,Nadiya Ke Paar,0.2732,0.000,0.884,0.116

In [48]:
#Sentiment Analysis
def percentage(part,whole):
    return 100 * float(part)/float(whole)

#Assigning Initial Values
positive = 0
negative = 0
neutral = 0
#Creating empty lists
summary_list = []
neutral_list = []
negative_list = []
positive_list = []

In [49]:
#Iterating over the Summary in the dataframe
for summary in df['Text']:
    summary_list.append(summary)
    analyzer = SentimentIntensityAnalyzer().polarity_scores(summary)
    neg = analyzer['neg']
    neu = analyzer['neu']
    pos = analyzer['pos']
    comp = analyzer['compound']
    
    if neg > pos:
        negative_list.append(summary) #appending the tweet that satisfies this condition
        negative += 1 #increasing the count by 1
    elif pos > neg:
        positive_list.append(summary) #appending the tweet that satisfies this condition
        positive += 1 #increasing the count by 1
    elif pos == neg:
        neutral_list.append(summary) #appending the tweet that satisfies this condition
        neutral += 1 #increasing the count by 1 

positive = percentage(positive, len(df)) #percentage is the function defined above
negative = percentage(negative, len(df))
neutral = percentage(neutral, len(df))

In [50]:
#Converting lists to pandas dataframe
summary_list = pd.DataFrame(summary_list)
neutral_list = pd.DataFrame(neutral_list)
negative_list = pd.DataFrame(negative_list)
positive_list = pd.DataFrame(positive_list)
#using len(length) function for counting
print("Last 30 days, there have been", len(summary_list) ,  "tweets on Energy Consumption" ,  end='\n')
print("Positive Sentiment:", '%.2f' % len(positive_list), end='\n')
print("Neutral Sentiment:", '%.2f' % len(neutral_list), end='\n')
print("Negative Sentiment:", '%.2f' % len(negative_list), end='\n')

Last 30 days, there have been 3583 tweets on Energy Consumption
Positive Sentiment: 2266.00
Neutral Sentiment: 693.00
Negative Sentiment: 624.00

In [51]:
df.to_csv('Twitter_Enery_output.csv',mode='a',index = False, header=None)